version: '3'
services: 
  component:
    # for building from source
    image: qanary/qanary-component-mt-python-nllb:0.2.0
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SERVICE_NAME_COMPONENT=MT-NLLB
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/
    network_mode: host
