version: '3'
services: 
  mt-nllb:
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    volumes:
      - /path/to/huggingface-docker-cache:/root/.cache/huggingface/transformers # for caching huggingface models

