PREFIX  qa:   <http://www.wdaqua.eu/qa#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  oa:   <http://www.w3.org/ns/openannotation/core/>

INSERT {
  GRAPH <urn:graph> {
    <urn:answer> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> qa:Answer .
    ?a <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> qa:AnnotationOfAnswerSPARQL .
    ?a oa:hasTarget <urn:answer> .
    ?a oa:hasBody "generatedQuery" .
    ?a oa:annotatedBy <urn:qanary:applicationName> .
    ?a oa:annotatedAt ?time .
  }
}
WHERE
  { BIND(iri(str(rand())) AS ?a)
    BIND(now() AS ?time)
  }
