= ChatGPT Wrapper

== Description

This component is a wrapper for the https://platform.openai.com/overview[OpenAI API].
It sends the given question to the https://platform.openai.com/docs/api-reference/completions[completions API]
and store all returned choices in the graph.

== Configuration

This component requires the following environment variables to be set:
----
chatgpt.api.key=
----

**chatgpt.api.key**: The API key for the OpenAI API.

You can change the default values for the following parameters in the application.properties file:
----
question_controller.corss.origin=*
chatgpt.base.url=https://api.openai.com
chatgpt.model=text-davinci-003
chatgpt.suffix=null
chatgpt.maxTokens=16
chatgpt.temperature=1.0
chatgpt.topP=1.0
chatgpt.n=1
chatgpt.stream=false
chatgpt.echo=false
chatgpt.stop=null
chatgpt.presencePenalty=0.0
chatgpt.frequencyPenalty=0.0
chatgpt.bestOf=1
chatgpt.user=null
chatgpt.api.live.test.active.test=true
----

- **question_controller.corss.origin**: The CORS origin for the question controller.
- **chatgpt.base.url**: The base URL for the OpenAI API.
**chatgpt.api.live.test.active**: If true, the component will run a live test on start up.

- **chatgpt.model**: The model to use for the completion.
A complete list of the supported models can be found https://platform.openai.com/docs/models[here]

All Information for the following properties can be found https://platform.openai.com/docs/api-reference/completions/create[here]

- chatgpt.suffix
- chatgpt.maxTokens
- chatgpt.temperature
- chatgpt.topP
- chatgpt.n
- chatgpt.stream
- chatgpt.echo
- chatgpt.stop
- chatgpt.presencePenalty
- chatgpt.frequencyPenalty
- chatgpt.bestOf
- chatgpt.user

== Input specification

This component takes as input the question.

== Output specification

[source,ttl]
----
PREFIX  qa:   <http://www.wdaqua.eu/qa#>
PREFIX  oa:   <http://www.w3.org/ns/openannotation/core/>
PREFIX  dbr:  <http://dbpedia.org/resource/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT {
  GRAPH <urn:qanary#outGraph> {
    ?newAnnotation rdf:type qa:AnnotationOfTextAnswerJson .
    ?newAnnotation oa:hasTarget <urn:qanary#endpoint> .
    ?newAnnotation oa:hasBody ?answer .
    ?newAnnotation oa:annotatedAt ?time .
    ?newAnnotation oa:annotatedBy <urn:qanary:ChatGPTWrapper> .
    ?answer rdf:type qa:AnswerJson .
    ?answer rdf:value "{\"choices\":[{\"text\":\"\\n\\nThis is indeed a test\",\"index\":0,\"finish_reason\":\"length\"}]}" .
    qa:AnswerJson rdfs:subClassOf qa:Answer .
  }
}
WHERE
{
    BIND(iri(str(rand())) AS ?newAnnotation)
    BIND(iri(str(rand())) AS ?answer)
    BIND(now() AS ?time)
}
----
