PREFIX  qa:   <http://www.wdaqua.eu/qa#>
PREFIX  oa:   <http://www.w3.org/ns/openannotation/core/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  *
FROM <urn:graph>
WHERE
  { ?annotationId
              rdf:type        qa:AnnotationOfInstance ;
              oa:hasTarget    _:b0 .
    _:b0      rdf:type        oa:SpecificResource ;
              oa:hasSource    <urn:source> ;
              oa:hasSelector  _:b1 .
    _:b1      rdf:type        oa:TextPositionSelector ;
              oa:start        "5"^^<http://www.w3.org/2001/XMLSchema#int> ;
              oa:end          ?end .
    ?annotationId
              oa:hasBody      ?hasBody ;
              oa:annotatedBy  ?annotatedBy ;
              oa:annotatedAt  ?annotatedAt
    OPTIONAL
      { ?annotationId
                  qa:score  ?score
      }
  }
