:toc:
:toclevels: 3
:source-highlighter: highlight.js
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]

= Expected Answer Type (EAT) classification component

toc::[]

== Intention

The component classifies the DBpedia answer type of a textual question.

== Behavior

As a Qanary component, it reads the question and the annotations produced by upstream components from the Qanary triplestore (the shared process memory), performs its task — predict the expected answer type of the question — and writes the result back as standard Qanary (Web Annotation / `qa:`) annotations. See <<Input specification>> / <<Output specification>> below for the exact annotation contract.

== Characteristics

* *Task type:* Expected Answer Type (EAT).
* *Knowledge base:* DBpedia.
* *Runtime:* containerised; some models/services may need to be downloaded on first run.

== Implementation

* *Language:* Python 3.
* *Major frameworks:* `qanary-helpers`, Flask (with SPARQLWrapper).
* *Tests:* no automated tests in this component.

== Build and run

Build and run the containerised component (configure the `.env` / environment first):

[source,bash]
----
docker compose up --build
# or, for local development:
pip install -r requirements.txt && python run.py
----

== Input specification

Not applicable as the textual question is a default parameter

== Output specification

[source,ttl]
----
@prefix qa: <http://www.wdaqua.eu/qa#> .
@prefix oa: <http://www.w3.org/ns/openannotation/core/> .
@prefix dbo: <http://dbpedia.org/ontology/> .

<urn:qanary:output> a qa:AnnotationOfQuestionTranslation ;
    oa:hasTarget <urn:myQanaryQuestion>; 
    oa:hasBody dbo:Answer_Type ;
    oa:annotatedBy <urn:qanary:PythonEATclassifier> ;
    oa:annotatedAt "2001-10-26T21:32:52"^^xsd:dateTime .
----

For example:

* question: "Where was Angela Merkel born?";
* answer type: "Place"

The answer type taxonomy is using the top-level classes of
the http://mappings.dbpedia.org/server/ontology/classes/[DBpedia Ontology]. Hence, the result is always a DBpedia
concept.

The component is integrating a classification model that was pretrained using Tensorflow. The model is served as
external component by https://www.tensorflow.org/tfx/guide/serving[Tensorflow Serving]. Hence, this EAT classification
is following the structure of a Qanary Wrapper component.

== Usage

1. Clone the Git repository of the collected Qanary components: 

[source,bash]
----
git clone https://github.com/WDAqua/Qanary-question-answering-components.git
----

2. Switch to the component's directory: 

[source,bash]
----
cd Qanary-question-answering-components/qanary_component-Python-QC-EAT-classifier
----

3. Build the Docker container: 

[source,bash]
----
docker build -t eat-component:latest .
----

6. Run the Docker container with the following environment variables (here it is assumed that the service uses port 41097, all values can be changed w.r.t. your individual needs):
[source,bash]
----
docker run -d -p 41097:41097 \
    -e SPRING_BOOT_ADMIN_URL='http://webengineering.ins.hs-anhalt.de:43740' \
    -e SPRING_BOOT_ADMIN_USERNAME='admin' \
    -e SPRING_BOOT_ADMIN_PASSWORD='admin' \
    -e SERVICE_HOST='http://webengineering.ins.hs-anhalt.de' \
    -e SERVICE_PORT=41097 \
    -e SERVICE_NAME_COMPONENT='EAT-Component' \
    -e SERVICE_DESCRIPTION_COMPONENT='EAT-Component-Description' \
    -e CLASSIFICATION_ENDPOINT='http://webengineering.ins.hs-anhalt.de:41066/answer_type_classifier/predict' \
    eat-component:latest
----

The component can be run with HTTPS. For this you need to start the container with a volume
pointing to a certificate (.cert) and keyfile (.key).
The file paths to certificate and keyfile are passed with parameters `SERVER_SSL_CERTIFICATE` and
`SERVER_SSL_KEY`.
The `SERVICE_HOST` parameter has to be set to `https://...`.

The run command could look something like this:

[source,bash]
----
docker run -d -p 41097:41097 \
    -e SPRING_BOOT_ADMIN_URL='http://webengineering.ins.hs-anhalt.de:43740' \
    -e SPRING_BOOT_ADMIN_USERNAME='admin' \
    -e SPRING_BOOT_ADMIN_PASSWORD='admin' \
    -e SERVICE_HOST='https://webengineering.ins.hs-anhalt.de' \
    -e SERVICE_PORT=41097 \
    -e SERVICE_NAME_COMPONENT='EAT-Component' \
    -e SERVICE_DESCRIPTION_COMPONENT='EAT-Component-Description' \
    -e CLASSIFICATION_ENDPOINT='http://webengineering.ins.hs-anhalt.de:41066/answer_type_classifier/predict' \
    -e SERVER_SSL_CERTIFICATE='/certificate/server.cert' \
    -e SERVER_SSL_KEY='/certificate/server.key' \
    -v /home/user/certificate/:/certificate/ \
    eat-component:latest
----

The parameters description:

* `SPRING_BOOT_ADMIN_URL` -- URL of the Qanary pipeline (see Step 1 and Step 2 of
  the https://github.com/WDAqua/Qanary/wiki/Qanary-tutorial:-How-to-build-a-trivial-Question-Answering-pipeline[tutorial])
* `SPRING_BOOT_ADMIN_USERNAME` -- the admin username of the Qanary pipeline
* `SPRING_BOOT_ADMIN_PASSWORD` -- the admin password of the Qanary pipeline
* `SERVICE_HOST` -- the host of your Qanary component without protocol prefix (e.g., `http://`). It has to be visible to
  the Qanary pipeline (i.e., a callback from the Qanary pipeline can be executed).
* `SERVICE_PORT` -- the port of your Qanary component (has to be visible to the Qanary pipeline)
* `SERVICE_NAME_COMPONENT` -- the name of your Qanary component (for better identification)
* `SERVICE_DESCRIPTION_COMPONENT` -- the description of your Qanary component
* `CLASSIFICATION_ENDPOINT` -- the endpoint of the classifier deployed by using https://www.tensorflow.org/tfx/guide/serving[Tensorflow Serving]. This parameter must not be changed unless you have your own endpoint.

After execution component creates Qanary annotations in the Qanary triplestore with the following predicates:

* `qa:hasAnswerType` -- the predicted answer type;
* `oa:annotatedBy` -- the name of the component;
* `oa:annotatedAt` -- the time of the prediction.
