PREFIX  qa:   <http://www.wdaqua.eu/qa#>
PREFIX  oa:   <http://www.w3.org/ns/openannotation/core/>
PREFIX  dbr:  <http://dbpedia.org/resource/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?annotation ?wikidataQuery ?annotationScore
FROM ?graph
WHERE {
			?annotation  
				rdf:type	qa:AnnotationOfAnswerSPARQL ;
              	oa:hasBody	?wikidataQueryData .
		    FILTER(isLiteral(?wikidataQueryData)).
    		BIND(?wikidataQueryData AS ?wikidataQuery ).
		    ?annotation  
		    	qa:score 	?annotationScore ;
             	oa:hasTarget ?targetQuestion
}