version: '3'
services:
  qanary-component-rel-python-falcon: # for building from source
    # or use image: qanary/qanary-component-rel-python-falcon:latest
    image: qanary/qanary-component-rel-python-falcon:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: $SERVICE_NAME_COMPONENT
    network_mode: host # usage of ports also possible