PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>

INSERT {
    GRAPH ?graph {
        ?a a qa:AnnotationOfQuestionLanguage .
        ?a oa:hasBody ?language .
        ?a oa:hasTarget ?targetQuestion ;
           oa:annotatedBy ?application ;
           oa:annotatedAt ?time
    }
}

WHERE {
    BIND (IRI(str(RAND())) AS ?a) .
    BIND (now() as ?time) .
}