PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?resource foaf:name ?answer .# real name of superhero
  ?resource rdfs:label ?label .# get the character name of the superhero
  FILTER(LANG(?label) = "en") .# only English names
  ?resource dct:subject dbr:Category:Superheroes_with_alter_egos .# only superheros
  FILTER(! strStarts(LCASE(?label), LCASE(?answer))).# filter starting with the same name
  VALUES ?resource { ?dbpediaResource } .# only for this specific resource
}
ORDER BY ?resource