version: '3'
services:
  component:
    # for building from source
    image: qanary-component-mt-python-helsinki:latest
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SERVICE_NAME_COMPONENT=MT-Helsinki-all
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/
    network_mode: host
