version: '3'
services:

  component-en-de:
    # for building from source
    image: qanary-component-mt-python-helsinki-en-de:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SOURCE_LANGUAGE=en
        - TARGET_LANGUAGE=de
    env_file:
      - .env
    environment:
      - SERVICE_NAME_COMPONENT=MT-Helsinki-en-de
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/
    network_mode: host

  component-en-ru:
    # for building from source
    image: qanary-component-mt-python-helsinki-en-ru:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SOURCE_LANGUAGE=en
        - TARGET_LANGUAGE=ru
    env_file:
      - .env
    environment:
      - SERVICE_NAME_COMPONENT=MT-Helsinki-en-ru
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/
    network_mode: host


  component-en-es:
    # for building from source
    image: qanary-component-mt-python-helsinki-en-es:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SOURCE_LANGUAGE=en
        - TARGET_LANGUAGE=es
    env_file:
      - .env
    environment:
      - SERVICE_NAME_COMPONENT=MT-Helsinki-en-es
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/
    network_mode: host


  component-de-en:
    # for building from source
    image: qanary-component-mt-python-helsinki-de-en:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SOURCE_LANGUAGE=de
        - TARGET_LANGUAGE=en
    env_file:
      - .env
    environment:
      - SERVICE_NAME_COMPONENT=MT-Helsinki-de-en
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/
    network_mode: host


  component-ru-en:
    # for building from source
    image: qanary-component-mt-python-helsinki-ru-en:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SOURCE_LANGUAGE=ru
        - TARGET_LANGUAGE=en
    env_file:
      - .env
    environment:
      - SERVICE_NAME_COMPONENT=MT-Helsinki-ru-en
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/
    network_mode: host


  component-es-en:
    # for building from source
    image: qanary-component-mt-python-helsinki-es-en:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SOURCE_LANGUAGE=es
        - TARGET_LANGUAGE=en
    env_file:
      - .env
    environment:
      - SERVICE_NAME_COMPONENT=MT-Helsinki-es-en
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/
    network_mode: host
