version: "3.5"
services:

  # local libretranslate server
  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/

  # component
  component:
    # for building from source
    image: qanary-component-mt-python-libretranslate:latest
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
