services:

  # local libretranslate server
  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/

  # component
  component:
    # for building from source
    image: qanary/qanary-component-mt-python-libretranslate:0.2.0
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SERVICE_NAME_COMPONENT=MT-LibreTranslate
