version: "3.5"
services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - "./models:/home/libretranslate/.local/cache"
  # component
  component:
    image: qanary-component-mt-python-libretranslate:${SERVICE_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
#  # tag latest
#  latest:
#    extends: component
#    image: qanary-component-mt-python-libretranslate:latest
