prefix qa: <http://www.wdaqua.eu/qa#>
prefix oa: <http://www.w3.org/ns/openannotation/core/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
GRAPH ?graph {
    ?a a qa:AnnotationOfSpotInstance .
    ?a oa:hasTarget [
        a    oa:SpecificResource;
        oa:hasSource    ?targetQuestion;
        oa:hasSelector  [
            a oa:TextPositionSelector ;
            oa:start ?begin ;
            oa:end  ?end .
        ] .
    ] ;
    oa:annotatedBy ?application ;
    oa:annotatedAt ?time .
}}
WHERE {
    SELECT ?a ?s ?begin ?end ?time
    WHERE {
        graph ?tmpGraph {
            ?s	<http://ns.aksw.org/scms/beginIndex> ?begin .
            ?s  <http://ns.aksw.org/scms/endIndex> ?end .
            BIND (IRI(str(RAND())) AS ?a) .
            BIND (now() as ?time) .
        }
    }
}