= QB ComicCharacterAlterEgoSimpleQueryBuilder component

== Description

Receives a disambiguated entity and builds a SPARQL query over Wikidata about all the data related to birth of an entity

== Input specification

Comment: non-standard type `qa:AnnotationOfSpotInstance` is used

[source, ttl]
----
@prefix qa: <http://www.wdaqua.eu/qa#> .
@prefix oa: <http://www.w3.org/ns/openannotation/core/> .

<urn:qanary:input> a qa:AnnotationOfSpotInstance .
<urn:qanary:input> oa:hasTarget [
    a    oa:SpecificResource;
    oa:hasSource    <urn:qanary:myQanaryQuestion> ;
    oa:hasSelector  [
        a oa:TextPositionSelector ;
        oa:start "0"^^xsd:nonNegativeInteger ;
        oa:end  "5"^^xsd:nonNegativeInteger
    ]
] .
<urn:qanary:input> oa:annotatedAt "2001-10-26T21:32:52"^^xsd:dateTime .
----

== Output specification

Comment: complex `oa:hasTarget` is used

[source, ttl]
----
@prefix qa: <http://www.wdaqua.eu/qa#> .
@prefix oa: <http://www.w3.org/ns/openannotation/core/> .

<urn:qanary:output> a qa:AnnotationOfAnswerSPARQL ;
    oa:hasTarget [
	    a    oa:SpecificResource ;
	    oa:hasSource    <urn:qanary:qanaryQuestion.getUri> ;
    ] ;
    oa:hasBody "sparql query" ;
    qa:score "0.5"^^xsd:float ;
    oa:annotatedAt "2001-10-26T21:32:52"^^xsd:dateTime ;
    oa:annotatedBy <urn:qanary:applicationName > .
----

== Build and run

This component targets the current *Qanary framework 4.0.0* (Spring Boot 3,
Java 21). Install the framework first (`mvn install` in the
https://github.com/WDAqua/Qanary[Qanary] repository), then build clean:

[source,bash]
----
JAVA_HOME=/path/to/jdk21 mvn clean package
java -jar target/qanary-component-qb-comiccharacteralteregosimpledbpedia.jar
----

Docker:

[source,bash]
----
mvn clean package
docker build --build-arg JAR_FILE=target/qanary-component-qb-comiccharacteralteregosimpledbpedia.jar \
  -t qanary/qanary-component-qb-comiccharacteralteregosimpledbpedia .
----

Configuration is in `src/main/resources/config/application.properties`
(`server.port`, `spring.application.name`, `spring.boot.admin.url`).

== Tests

`mvn test` runs the full-context `QanaryServiceControllerTest` and `QueryTest`.
The Spring Boot Admin client failing to reach a non-running pipeline is logged but
non-fatal.
