[pytest]
log_cli = 0
env =
    PRODUCTION=True
    SERVICE_NAME_COMPONENT=QB-Python-RuleBasedQueryBuilder
    SERVICE_DESCRIPTION_COMPONENT=Rule-based query builder generating SPARQL from annotated entities and predicates
    KNOWLEDGE_GRAPH_ENDPOINT=
    MAX_ANNOTATIONS_PER_TYPE=2
    MAX_STORED_CANDIDATES=3
    SERVER_HOST=http://localhost
    SERVER_PORT=8080
    SPRING_BOOT_ADMIN_URL=http://localhost:8080
    SPRING_BOOT_ADMIN_USERNAME=admin
    SPRING_BOOT_ADMIN_PASSWORD=admin
filterwarnings =
    ignore:Dataset.default_context is deprecated:DeprecationWarning
