version: '3'
services:
  qanary-component-qe-python-sparqlexecuter:
    # or use image: qanary/qanary-component-qe-python-sparqlexecuter:latest # for using the image from dockerhub
    image: qanary/qanary-component-qe-python-sparqlexecuter:latest
    build: # for building from source
      context: .
      dockerfile: Dockerfile
    network_mode: host # or use ports
    env_file: 
     - .env