version: '3'
services:
  qe-python-sparqlexecuter:
    build: # for building from source
      context: .
      dockerfile: Dockerfile
    # or use image: qanary/qanary-component-qe-python-sparqlexecuter:latest # for using the image from dockerhub
    network_mode: host # or use ports
    env_file: 
     - .env
    command: uvicorn component:app --host 0.0.0.0 --port=$SERVER_PORT