= NER DBpedia Spotlight

== Description

Receives a textual question, forwards it to DBpedia Spotlight API and writes result in JSON format.

Comment: This component does the same thing as the corresponding NED, but just saves not all the information.

== Input specification

Not applicable as the textual question is a default parameter

== Output specification

Comment: no score in the output

[source, ttl]
----
@prefix qa: <http://www.wdaqua.eu/qa#> .
@prefix oa: <http://www.w3.org/ns/openannotation/core/> .

<urn:qanary:output> a qa:AnnotationOfSpotInstance .
<urn:qanary:output> oa:hasTarget [
    a   oa:SpecificResource;
        oa:hasSource    <urn:qanary:myQanaryQuestion> ;
        oa:hasSelector  [
            a oa:TextPositionSelector ;
            oa:start "0"^^xsd:nonNegativeInteger ;
            oa:end  "5"^^xsd:nonNegativeInteger
        ]
    ] .
<urn:qanary:output> oa:annotatedBy <urn:qanary:NER-DBpediaSpotlight> ;
    oa:annotatedAt "2001-10-26T21:32:52"^^xsd:dateTime .
----

== Build and run

This component targets the current *Qanary framework 4.0.0* (Spring Boot 3,
Java 21). Install the framework first (`mvn install` in the
https://github.com/WDAqua/Qanary[Qanary] repository), then build clean:

[source,bash]
----
JAVA_HOME=/path/to/jdk21 mvn clean package
java -jar target/qanary-component-ner-dbpediaspotlight.jar
----

Docker:

[source,bash]
----
mvn clean package
docker build --build-arg JAR_FILE=target/qanary-component-ner-dbpediaspotlight.jar \
  -t qanary/qanary-component-ner-dbpediaspotlight .
----

== Tests

`mvn test` runs offline unit tests (mocked DBpedia Spotlight responses + the
framework cache test). The Spring Boot Admin client failing to reach a
non-running pipeline is logged but non-fatal.
