PREFIX qa:<http://www.wdaqua.eu/qa#>

SELECT ?lang
FROM ?graph
WHERE {
    ?q a qa:Question .
    ?anno <http://www.w3.org/ns/openannotation/core/hasTarget> ?q .
    ?anno <http://www.w3.org/ns/openannotation/core/hasBody> ?lang .
    ?anno a qa:AnnotationOfQuestionLanguage .
}