version: '3'
services: 
  build:
    # for building from source
    image: qanary-component-mt-python-mbart:latest
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
