version: '3'
services: 
  build:
    image: qanary-component-mt-python-mbart
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
  # tag latest
  latest:
    extends: build
    image: qanary-component-mt-python-mbart:latest
  # tag version
  version:
    extends: build
    image: qanary-component-mt-python-mbart:${SERVICE_VERSION:-latest}
