PREFIX  qa:   <http://www.wdaqua.eu/qa#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  oa:   <http://www.w3.org/ns/openannotation/core/>
PREFIX  dbr:  <http://dbpedia.org/resource/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT {
  GRAPH <urn:graph> {
    ?newAnnotation rdf:type qa:AnnotationOfAnswerSPARQL .
    ?newAnnotation oa:hasTarget _:b0 .
    _:b0 rdf:type oa:SpecificResource .
    _:b0 oa:hasSource <urn:targetQuestion> .
    ?newAnnotation oa:hasBody "dbpediaQuery" .
    ?newAnnotation qa:score "1.0"^^xsd:float .
    ?newAnnotation oa:annotatedAt ?time .
    ?newAnnotation oa:annotatedBy <urn:qanary:applicationName> .
  }
}
WHERE
  { BIND(IRI(str(rand())) AS ?newAnnotation)
    BIND(now() AS ?time)
  }
