PREFIX  qa:   <http://www.wdaqua.eu/qa#>
PREFIX  oa:   <http://www.w3.org/ns/openannotation/core/>

SELECT  ?a ?dbpediaResource ?startOfSpecificResource ?endOfSpecificResource ?annotatorComponent ?time
FROM <urn:graph>
WHERE
  { VALUES ?dbpediaResource { <urn:targetQuestion> }
    ?a    a               qa:AnnotationOfSpotInstance ;
          oa:hasTarget    _:b0 .
    _:b0  a               oa:SpecificResource ;
          oa:hasSource    ?dbpediaResource ;
          oa:hasSelector  _:b1 .
    _:b1  a               oa:TextPositionSelector ;
          oa:start        ?startOfSpecificResource ;
          oa:end          ?endOfSpecificResource .
    ?a    oa:annotatedAt  ?time
  }
