name: Qanary Component Build Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    env:
      BABELFY_API_KEY: ${{ secrets.BABELFY_API_KEY }}
      CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      DANDELION_API_KEY: ${{ secrets.DANDELION_API_KEY }}
      MEANINGCLOUD_API_KEY: ${{ secrets.MEANINGCLOUD_API_KEY }}
      TAGME_API_KEY: ${{ secrets.TAGME_API_KEY }}
      TEXTRAZOR_API_KEY: ${{ secrets.TEXTRAZOR_API_KEY }}
    steps:
      - name: Configure java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - name: Build and push Java components
        run: bash -c ./service_config/build_images.sh
      - name: Init update
        uses: MindMaster98/docker-service-updater@v0.2.1
        with:
          api_key: ${{ secrets.API_KEY }}
          updater_host: ${{ secrets.UPDATER_HOST }}
  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - name: Build and push Python components
        run: bash -c ./service_config/build_python_images.sh
      - name: Init update
        uses: WSE-research/docker-service-updater@v0.2.1
        with:
          api_key: ${{ secrets.API_KEY }}
          updater_host: ${{ secrets.UPDATER_HOST }}
