name: Qanary Component Build Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Build the Docker images and Push to Dockerhub
        run: bash -c ./service_config/build_images.sh
      - name: Init update
        env:
          API_KEY: ${{ secrets.API_KEY }}
          UPDATER_HOST: ${{ secrets.UPDATER_HOST }}
        run: cd service_config && python init_services.py update