# retrieve an annotation typed AnnotationOfInstance from the Qanary triplestore
PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>

SELECT *
FROM ?graphID
WHERE {
    ?annotationId a qa:AnnotationOfInstance .
    ?annotationId oa:hasTarget [
        a    oa:SpecificResource;
        oa:hasSource    ?targetQuestion;
        oa:hasSelector  [
            a oa:TextPositionSelector ;
            oa:start ?start ;
            oa:end  ?end
        ]
    ] .
    ?annotationId oa:hasBody ?resource ;
    qa:score ?score .
}
