# find the URI of the resource in the Wikidata knowledge graph
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?resource
WHERE {
  ?originResource owl:sameAs ?resource .
  FILTER (STRSTARTS(STR(?resource), "http://www.wikidata.org"))
}